project:
  type: website

website:
  title: "Homepage"

  announcement:
    icon: tools
    content: "This website is under active development. I am currently updating project details, results, and documentation."

  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Skills
        href: skills.qmd
      - text: Experience
        href: experience.qmd
      - text: Projects
        href: projects.qmd
      - text: Blogposts
        href: blog-posts/index.qmd
    right:
      - icon: github
        href: https://github.com/DeenaLad
      - icon: linkedin
        href: https://www.linkedin.com/in/deena-lad-307645214/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full
    fig-align: center
